### PR TITLE
rethinkDB token-auth dialog fetch

### PR DESCRIPTION
**Pull request by kristianmandrup**
More plugins...

### CODE REVIEW

**Comment by zewa666** [comment]
I'm not sure whether @PWKad and @Aaike are going to prefer to register the new official [Aurelia Dialog Plugin](https://github.com/aurelia/dialog) instead of their current custom repos.

**Comment by kristianmandrup** [comment]
Then ask them and take what you like from this PR ;)

**Comment by zewa666** [comment]
That's why I referenced them above :)
Thanks for your contribution :+1:

**Comment by EisenbergEffect** [comment]
We've definitely got an official dialog plugin that is combining all ideas. So, that will be the one in the registry ultimately.

**Pull request merged**
